config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :books
  root to: 'homes#top'
  # get 'edit' => 'books#edit'
  get 'books' => 'books#index'
  # get 'show' => 'books#show'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all
    
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = 'Book was successfully created.'
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
    
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice] = 'Book was successfully updated.'
       redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    flash[:notice] = 'Book was successfully destroyed.'
    redirect_to books_path  # 投稿一覧画面へリダイレクト
  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
   
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<body>
<!--編集成功メッセージここから-->
<p id="notice"><%= flash[:notice] %></p>
<!--編集成功メッセージここまで-->

<h1>Editing Book</h1>

<!--エラーメッセージここから-->
<% if @book.errors.any? %>
<div id="error_explanation">
   <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
   <ul>
     <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
   </ul>
</div>
<% end %>
<!--エラーメッセージここまで-->

<div class="form">
 <%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>

  <div class="field">
    <div class="label">Title</div>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <div class="label">Body</div>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit 'Update Book' %>
  </div>
 <% end %>
</div>

<%= link_to "Show", "/books/#{@book.id}" %> |
<%= link_to "Back", books_path %>
</body>

app/views/books/index.html.erb
<body>
<!--削除成功メッセージここから-->
<p id="notice"><%= flash[:notice] %></p>
<!--削除成功メッセージここまで-->

<h1>Books</h1>

<table>
   <thead>
     <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
     </tr>
    </thead>
    
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show", "/books/#{book.id}" %></td>
        <td><%= link_to "Edit", edit_book_path(book.id) %></td>
        <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
     </tr>
      <% end %>
  </tbody>
</table>

<h2>New book</h2>
<!--エラーメッセージここから-->
<% if @book.errors.any? %>
<div id="error_explanation">
   <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
   <ul>
     <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
   </ul>
</div>
<% end %>
<!--エラーメッセージここまで-->

<div class="form">
   <%= form_with model:@book, url:'/books', local:true do |f| %>
   <div class="field">
     <div class="label">Title</div>
     <%= f.text_field :title %>
   </div>
   <div class="field">
     <div class="label">Body</div>
     <%= f.text_area :body %>
   </div>
   <div class="actions">
     <%= f.submit 'Create Book' %>
   </div>
   <% end %>
</div>

</body>

app/views/books/show.html.erb
<body>
<!--投稿成功メッセージここから-->
<p id="notice"><%= flash[:notice] %></p>
<!--投稿成功メッセージここまで-->

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @book.body %>
</p>

<%= link_to "Edit", edit_book_path(@book.id) %> |
<%= link_to "Back", books_path %>
</body>

app/views/homes/top.html.erb
<body>
  <h1>ようこそ <strong>Bookers</strong>  へ！</h1>
  <p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p>
  <p>印象を共有し交換することができます</p>
  <div class="link">
   <p><%= link_to "start", books_path %></p>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>